groups:
  - name: aspnet_rules
    rules:
      - record: aspnet:http_requests:rate5m
        expr: rate(http_requests_received_total[5m])

      - record: aspnet:http_request_duration:p95
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))

      - record: aspnet:error_rate
        expr: rate(http_requests_received_total{code=~"5.."}[5m]) / rate(http_requests_received_total[5m])